version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/python37/Dockerfile
    ports:
      - "4000:4000" 
    volumes:
      - .:/usr/src/address_app
    container_name: al-addressbook-app
    # command: tail -f /dev/null